### ISSUE TITLE
recaptcha doesnt show up inside easytabs

### ISSUE THREAD

**Issue by sarrafj** [StudioForty9/Recaptcha#6]
i am not able to load the recaptcha inside easytabs of a review form. the independent review form is able to load captcha but not inside the easytab. calling the code in local.xml file doesnt works. which xml file i should try ?

**Comment by eoghanobrien** [comment]
I don't know anything about easytab but you're probably just talking about basic Magento layout XML here so I would recommend that you find the block containing the 'review_form' in easytab and add the recaptcha block to that, don't forget to set the 'allow' data attribute on the recaptcha block. For example, on the ultimo theme, they have a block 'tabreviews' and in order to show the recaptcha widget, you do something like:

``` xml
<reference name="[YOUR EASYTAB BLOCK REFERENCE]">
    <block type="review/form" name="product.review.form" as="review_form">
      <block type="studioforty9_recaptcha/explicit" name="studioforty9.recaptcha.explicit" template="studioforty9/recaptcha/explicit.phtml">
        <action method="setAllow"><value>true</value></action>
      </block>
</reference>
```
