### ISSUE TITLE
User has to refresh on form fail to resubmit

### ISSUE THREAD

**Issue by ZayLong** [StudioForty9/Recaptcha#8]
Loving the extension, however theres an issue that comes up

Whenever a user fails to fill out a required field OR fails to check the capcha before submitting 

the user is unable to submit a form even if they refill the required fields, and this is only remedied if they refresh. 

You can try it out here, scroll down to submit a review using the form.

http://staging.theindustrysource.com/lil-wet-brush-display-12-ct.html

I'd appreciate any help or tips

**Comment by eoghanobrien** [comment]
Hi ZayLong,

I think the issue here is your cookie configuration rather than the recaptcha extension, the javascript in this template is pretty simple: https://github.com/StudioForty9/Recaptcha/blob/master/app/design/frontend/base/default/template/studioforty9/recaptcha/explicit.phtml#L21-L31

Nothing that would cause the issue you're describing.

I am seeing this message in console `'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.` not sure if that's related to your problem or not though.

Have you set a domain for cookies via configuration?

**Comment by ZayLong** [comment]
Woah I thought I responded to this, sorry for the severely delayed response.

I'll take a look at getting my cookies in order the extension seems to work beyond that.

However I do get "There was an error with the recaptcha code, please try again." now on submission, would that mainly deal with the account set up for google recaptcha?

**Comment by eoghanobrien** [comment]
@ZayLong - @dzmcclur investigated and found a solution to the issue, I've pushed up a fix now so I'm going to mark this as closed - if you're still having trouble, feel free to re-open.
